version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: nuxt_postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-my_db}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'

  imgproxy:
    image: ghcr.io/imgproxy/imgproxy:latest
    ports:
      - '8079:8080'
    environment:
      IMGPROXY_ALLOW_INSECURE_URLS: 'true'
      IMGPROXY_ALLOW_LOCALHOST_SOURCES: 'true'
      IMGPROXY_ALLOW_LOCAL_NETWORKS: 'true'
    extra_hosts:
      - '${IMAGE_BASE_URL}:host-gateway'
    restart: always

volumes:
  postgres_data:
