// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import path from 'path';
import { defineConfig, env } from 'prisma/config';

export default defineConfig({
   datasource: {
    url: env('DATABASE_URL'),
  },
  schema: path.join('prisma', 'schema'),
  migrations: {
    path: 'prisma/migrations',
  },
});
